services:
  ms-data-collector:
    build: ./data/data_collector
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - ms-ai
      - mongo
    environment:
      - ai_URL=http://ms-ai:5000
      - RIOT_API_KEY=${RIOT_API_KEY}
      - RIOT_ACCOUNT_URL=https://europe.api.riotgames.com/riot/account/v1/accounts/by-riot-id/
      - RIOT_MATCHES_URL=https://europe.api.riotgames.com/lol/match/v5/matches/
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB=match_data
  ms-core:
    build: ./ms-core
    container_name: ms-core
    ports:
      - "8181:8181"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-core:5432/ms_core
      SPRING_DATASOURCE_USERNAME: core_user
      SPRING_DATASOURCE_PASSWORD: core_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - postgres-core
  
  ms-ai:
    build: ./ai
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB=match_data
      - MONGO_RECOMS_COLLECTION=recommendations
  
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  postgres-core:
      image: postgres:16
      container_name: postgres-ms-core
      restart: unless-stopped
      environment:
        POSTGRES_DB: ms_core
        POSTGRES_USER: core_user
        POSTGRES_PASSWORD: core_password
      ports:
        - "5433:5432"
      volumes:
        - postgres_core_data:/var/lib/postgresql/data

volumes:
  mongo_data:
  postgres_core_data:
